# Generated by Django 5.0.6 on 2024-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
                ('docotor', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('Time', models.IntegerField()),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
